CREATE TABLE address (
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bid        varchar(40) NOT NULL,
    street     varchar(40) NOT NULL,
    number     varchar(10),
    user_id    varchar(40) NOT NULL
);